CREATE TABLE IF NOT EXISTS consensus_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_uid VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  simulation_id VARCHAR(64) NOT NULL,
  question_text TEXT NOT NULL,
  persona_platform VARCHAR(16) NOT NULL DEFAULT 'reddit',
  threshold_percent TINYINT UNSIGNED NOT NULL,
  poll_interval_seconds INT UNSIGNED NOT NULL DEFAULT 30,
  total_agents INT UNSIGNED NOT NULL,
  current_round_index INT UNSIGNED NOT NULL DEFAULT 0,
  last_answerable_agents INT UNSIGNED NOT NULL DEFAULT 0,
  last_yes_agents INT UNSIGNED NOT NULL DEFAULT 0,
  last_no_agents INT UNSIGNED NOT NULL DEFAULT 0,
  final_answer VARCHAR(8) NULL,
  final_answerable_agents INT UNSIGNED NULL,
  final_yes_agents INT UNSIGNED NULL,
  final_no_agents INT UNSIGNED NULL,
  completed_round_index INT UNSIGNED NULL,
  final_reason_short VARCHAR(255) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  last_polled_at DATETIME NULL,
  next_run_at DATETIME NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at DATETIME NULL,
  end_reason VARCHAR(32) NULL,
  error_text VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_consensus_task_uid (task_uid),
  KEY idx_consensus_tasks_sim_status (simulation_id, status),
  KEY idx_consensus_tasks_status_next (status, next_run_at),
  KEY idx_consensus_tasks_project_created (project_id, created_at),
  KEY idx_consensus_tasks_sim_created (simulation_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consensus_agent_judgments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  round_index INT UNSIGNED NOT NULL,
  agent_source_id VARCHAR(64) NOT NULL,
  agent_name VARCHAR(255) NOT NULL,
  candidate_answer VARCHAR(8) NULL,
  is_answerable TINYINT(1) NOT NULL DEFAULT 0,
  content_short VARCHAR(255) NOT NULL,
  evidence_title VARCHAR(255) NULL,
  evidence_url VARCHAR(512) NULL,
  evidence_time VARCHAR(128) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'completed',
  error_text VARCHAR(255) NULL,
  raw_response_json JSON NULL,
  polled_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_consensus_task_round_agent (task_id, round_index, agent_source_id),
  KEY idx_consensus_judgments_task_round (task_id, round_index),
  KEY idx_consensus_judgments_task_agent (task_id, agent_source_id),
  KEY idx_consensus_judgments_task_answer (task_id, round_index, candidate_answer, is_answerable),
  KEY idx_consensus_judgments_task_polled (task_id, polled_at),
  CONSTRAINT fk_consensus_judgments_task
    FOREIGN KEY (task_id) REFERENCES consensus_tasks(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
